# Site settings
title: ludovicl blog-notes
# tagline: And Tagline
email: ludoviclrds@gmail.com
# description: > # this means to ignore newlines until "baseurl:"
#   Hi, I’m a professional UI/UX designrer and web developer.
#   I love being minimal and creative.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ludovicl.fr" # the base hostname & protocol for your site
logourl: /assets/images/logo@2x.png # Site logo
author: "ludovicl"
domain: "ludovicl.fr"
# author_thumbnail: "/assets/images/avatar.jpg" # Author avatar
# Theme customization - please change from the defaults!
theme:
  # Color for sidebar bar, links, etc
  highlight_color: "#205081" #205081" # "#272935"
  # Social media links, leave blank to ignore
  social: 
    github: ludovicl
    twitter: ludovicl
    # facebook: gayanvirajith
    # gplus: +gayanvirajith
    # dribble: gayanvirajith
    # pinterest: gayanvirajith

  # Enable share buttons on post footer
  show_share_buttons: false

  # Show author picure, name and social links on post footer
  show_author_info: false

  # Disqus comments manager - shortname
  # disqus_shortname: gaya-webcreate

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: 
  google_webmaster_key: 

# Build settings
markdown: kramdown

# Permalinks
permalink:        pretty

# Pagination config
paginate: 3

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed
destination: /var/www/vhosts/ludovicl.fr/httpdocs
